"use client";
import { useEffect, useState } from "react";
import Navbar from "./components/Navbar";
import "./globals.css";

import { ChakraWrapper } from "./providers/ChakraProvider";
import { supabase } from "@/utils/supabase";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [session, setSession] = useState(null);

  useEffect(() => {
    supabase.auth.onAuthStateChange((event, session) => {
      console.log(event, session);
      setSession(session);
    });
  }, []);
  return (
    <html lang="en">
      <body>
        <ChakraWrapper>
          <Navbar session={session} />
          {children}
        </ChakraWrapper>
      </body>
    </html>
  );
}
