// "use client";

import Navbar from "./components/Navbar";
import "./globals.css";

import { ChakraWrapper } from "./providers/ChakraProvider";
import { SessionProvider, useSession } from "./providers/SessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraWrapper>
          <SessionProvider>
            <Navbar />
            {children}
          </SessionProvider>
        </ChakraWrapper>
      </body>
    </html>
  );
}
